version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    build: . # Das aktuelle Verzeichnis, in dem sich docker-compose.yml befindet
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: mydb
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
